jdk:
  - openjdk10
install:
  - echo "Running a custom install command"
  - ./gradlew clean
  - ./gradlew :codegen:runCodegen buildProps build -xtest -xspotbugsTest
  - ./gradlew publishToMavenLocal -xsignMavenPublication
